* Advent of Code

** Usage

I wouldn't recommend it. Generally though...

*** Yearly

0. Log back into advent of code and set the `*aoc-session*` in your lisp image.
1. Add a new module to the `advent.asd` system for the year. Make `main.lisp` depend on it.
2. Add the section for the year to the `@ADVENT` section in `main.lisp`.
3. Start a new test file for the year and wire it into `tests.lisp` and the ASDF system.

*** Daily

1. Add a new file component to the system definition in `advent.asd`.
2. At the repl, `(scaffold 2022 02)` or whatever the date is.
3. Load the advent system in the repl, jump to the package, open tests.

That's it. Get hacking!

*** Tests

Oh, yeah. You might be interested in making sure any changes don't break things.

The usual `(asdf:test-system :advent)` incantation should take care of you.

** Installation

** Author

+ Brit Butler (brit@kingcons.io)

** Copyright

Copyright (c) 2022 Brit Butler (brit@kingcons.io)

** License

Licensed under the MIT License.
